GET http://localhost:3001/auth
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tYnJlIjoiTWlndWVsIMOBbmdlbCIsImFwZWxsaWRvMSI6IkxpbmFyZXMiLCJhcGVsbGlkbzIiOiJNYXJ0w61uZXoiLCJjb3JyZW8iOiJhIiwiY29udHJhc2VueWEiOiIkMmIkMTAkQktPWGdKYy5mTGNqUVBNTGpLLm0xLnk1dHBWeHB0dzJMREp4azlsMzFnenBnL2ovWmduZm0iLCJnZW5lcm8iOjEsInByb3BpZXRhcmlvIjoxLCJlZGlmaWNpbyI6MSwiZXNjYWxlcmEiOjEsInBpc28iOjEsImxldHJhIjoiQSIsImFkbWluIjowLCJpYXQiOjE2ODk4NDU4NTUsImV4cCI6MTY4OTkzMjI1NX0.uFNXZ9GPojxdI_k9QSV52z73-q-boTLvUhJKiu-1Hq0