GET http://localhost:3001/users
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tYnJlIjoiYSIsImFwZWxsaWRvMSI6ImEiLCJhcGVsbGlkbzIiOiJhIiwiY29ycmVvIjoiYSIsImNvbnRyYXNlbnlhIjoiJDJiJDEwJDVzUVl6RDZISzluWTk1Tzc2dy8yMy5tc1V2bHRUMXZnWG5mVmNubWJkOWtmODZuQ3pleEIyIiwiZ2VuZXJvIjoxLCJwcm9waWV0YXJpbyI6MSwiZWRpZmljaW8iOjEsImVzY2FsZXJhIjoxLCJwaXNvIjoxLCJsZXRyYSI6IkEiLCJhZG1pbiI6MCwiaWF0IjoxNjkxNDA1MjU1LCJleHAiOjE2OTE0OTE2NTV9.5LVMGd5QkST20DNaO9Az20eGILQNcvIiHM-GBcVC-_I