GET http://localhost:3001/ranking_single
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tYnJlIjoiTWlndWVsIMOBbmdlbCIsImFwZWxsaWRvMSI6IkxpbmFyZXMiLCJhcGVsbGlkbzIiOiJNYXJ0w61uZXoiLCJjb3JyZW8iOiJhIiwiY29udHJhc2VueWEiOiIkMmIkMTAkQktPWGdKYy5mTGNqUVBNTGpLLm0xLnk1dHBWeHB0dzJMREp4azlsMzFnenBnL2ovWmduZm0iLCJnZW5lcm8iOjEsInByb3BpZXRhcmlvIjoxLCJlZGlmaWNpbyI6MSwiZXNjYWxlcmEiOjEsInBpc28iOjEsImxldHJhIjoiQSIsImFkbWluIjowLCJpYXQiOjE2ODk3ODM5MDQsImV4cCI6MTY4OTg3MDMwNH0.996fdNY1364cbKxR-auXfTeF396Oa6QPZs92E6weIA4