DELETE http://localhost:3001/tournament
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tYnJlIjoiYSIsImFwZWxsaWRvMSI6ImEiLCJhcGVsbGlkbzIiOiJhIiwiY29ycmVvIjoiYSIsImNvbnRyYXNlbnlhIjoiJDJiJDEwJDVzUVl6RDZISzluWTk1Tzc2dy8yMy5tc1V2bHRUMXZnWG5mVmNubWJkOWtmODZuQ3pleEIyIiwiZ2VuZXJvIjoxLCJwcm9waWV0YXJpbyI6MSwiZWRpZmljaW8iOjEsImVzY2FsZXJhIjoxLCJwaXNvIjoxLCJsZXRyYSI6IkEiLCJhZG1pbiI6MCwiaWF0IjoxNjkwODE5Mjg2LCJleHAiOjE2OTA5MDU2ODZ9.ITf1nYnGS-SzpOjct61l-y7h4pc0iafDhG_DoxM_LAw

{
    "idTournament": "7"
}