GET http://localhost:3001/rankingUserTable
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibm9tYnJlIjoiTWlndWVsIEFuZ2VsIiwiYXBlbGxpZG8xIjoiTGluYXJlcyIsImFwZWxsaWRvMiI6Ik1hcnTDrW5leiIsImNvcnJlbyI6Im1pZ3VlbEBnbWFpbC5jb20iLCJjb250cmFzZW55YSI6IiQyYiQxMCQ2czl6dm5qTFR3bnhrRktkQzZVREwuaGxDNXB3MmpKWTcySklMczN0UWcxMGJST1VTbGhWQyIsImdlbmVybyI6MSwicHJvcGlldGFyaW8iOjEsImVkaWZpY2lvIjoxLCJlc2NhbGVyYSI6MSwicGlzbyI6MSwibGV0cmEiOiJBIiwiYWRtaW4iOjAsImlhdCI6MTY5MDg4NzE1NiwiZXhwIjoxNjkwOTczNTU2fQ.qoOoZrF_nhSip8x0tvb9gx1YdHEwmimYHyIW7KKiwkY