GET http://localhost:3001/rankingTable
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tYnJlIjoiTWlndWVsIMOBbmdlbCIsImFwZWxsaWRvMSI6IkxpbmFyZXMiLCJhcGVsbGlkbzIiOiJNYXJ0w61uZXoiLCJjb3JyZW8iOiJhIiwiY29udHJhc2VueWEiOiIkMmIkMTAkQktPWGdKYy5mTGNqUVBNTGpLLm0xLnk1dHBWeHB0dzJMREp4azlsMzFnenBnL2ovWmduZm0iLCJnZW5lcm8iOjEsInByb3BpZXRhcmlvIjoxLCJlZGlmaWNpbyI6MSwiZXNjYWxlcmEiOjEsInBpc28iOjEsImxldHJhIjoiQSIsImFkbWluIjowLCJpYXQiOjE2OTAzOTQyMjIsImV4cCI6MTY5MDQ4MDYyMn0.MAZqdHWZyp4pm9Kc2qgemFuXl7z1NNK9-3WwPzNSZwY